default:
  image: alpine/git

variables:
  http_proxy: "${HTTP_PROXY}"
  https_proxy: "${HTTPS_PROXY}"
  no_proxy: "${NO_PROXY}"

stages:
  - test
  - build
  - package

include:
  - local: '/build/ci/build.yaml'
  - local: '/build/ci/test.yaml'
  - local: '/build/ci/package-installer.yaml'
  - local: '/build/ci/package-kaniko.yaml'