/*
 * Copyright (C) 2020 Intel Corporation
 * SPDX-License-Identifier: BSD-3-Clause
 */
package hvs

import "github.com/intel-secl/intel-secl/v3/pkg/model/hvs"

// FlavorTemplate response payload
// swagger:parameters FlavorTemplate
type FlavorTemplate struct {
	// in: body
	Body hvs.FlavorTemplate
}

// FlavorSchema response payload
// swagger:parameters FlavorSchema
type FlavorSchema struct {
	// in: body
	Body hvs.FlavorSchema
}

// ---

// swagger:operation GET /flavor-template/{flavortemplate_id} Flavortemplate Retrieve-FlavorTemplate
// ---
//
// description: |
//   Retrieves a flavor template.
//
// x-permissions: flavor-template:retrieve
// security:
//  - bearerAuth: []
// produces:
// - application/json
// parameters:
// - name: flavortemplate_id
//   description: Unique ID of the flavortemplate
//   in: path
//   required: true
//   type: string
//   format: uuid
// - name: include_deleted
//   description: To include 'lazy-deleted' templates.
//   in: query
//   required: false
//   type: string
//   format: bool
// - name: Accept
//   description: Accept header
//   in: header
//   type: string
//   required: true
//   enum:
//     - application/json
// responses:
//   '200':
//     description: Successfully retrieved the flavortemplate
//     content:
//       application/json
//     schema:
//       $ref: "#/definitions/FlavorTemplate"
//   '400':
//     description: Invalid or Bad request
//   '401':
//     description: Unauthorized request
//   '404':
//     description: Flavortemplate record not found
//   '500':
//     description: Internal server error
//
// x-sample-call-endpoint: https://hvs.com:8443/hvs/v2/flavor-template/d6f81340-b033-4fae-8ccf-795430f486e7
// x-sample-call-output: |
//   {
//       "id": "d6f81340-b033-4fae-8ccf-795430f486e7",
//       "label": "default_uefi",
//       "condition": [
//           "//meta/vendor='Linux'",
//           "//meta/tpm_version/='2.0'",
//           "//meta/uefi_enabled/='true' or //meta/suefi_enabled/='true'"
//       ],
//       "flavor-parts": {
//           "PLATFORM": {
//               "meta": {
//                   "vendor": "Linux",
//                   "tpm_version": "2.0",
//                   "uefi_enabled": true
//               },
//               "pcr_rules": [
//                   {
//                       "pcr": {
//                           "index": 0,
//                           "bank": "SHA256"
//                       },
//                       "pcr_matches": true
//                   }
//               ]
//           },
//           "OS": {
//               "meta": {
//                   "vendor": "Linux",
//                   "tpm_version": "2.0",
//                   "uefi_enabled": true
//               },
//               "pcr_rules": [
//                   {
//                       "pcr": {
//                           "index": 7,
//                           "bank": "SHA256"
//                       },
//                       "pcr_matches": null,
//                       "eventlog_includes": [
//                           "shim",
//                           "db",
//                           "kek",
//                           "vmlinuz"
//                       ]
//                   }
//               ]
//           }
//       }
//   }

// ---

// swagger:operation POST /flavor-template/ Flavortemplate Create-FlavorTemplate
// ---
// description: |
//   <b>Flavor Template</b>: Flavor templates are used to implement dynamic flavor generation.
//   The dynamic generation of flavor-parts will be implemented through the use of “flavor-templates”.
//   The goals of flavor-templates are…
//        1.	Be extendable to generate flavors for future scenarios (without code changes).
//        2.	Support the creation of flavor-parts for existing vendors (Linux, ESXI).
//        3.	Support the creation of flavor-parts for existing hardware scenarios (TXT, CBNT, SUEFI, etc.).
//        4.	Provide a default flavor-templates that generate pcrs/event-log measurements for Shim/UEFI/PFR/BMC.
//
//   The serialized Flavorgroup Go struct object represents the content of the request body.
//
//    | Attribute                      | Description|
//    |--------------------------------|------------|
//    | ID                             | Unique ID of flavor template. |
//    | Label                          | Name of the flavortemplate to be created. |
//    | Condition                      | The “condition” uses meta-data from the host-manifest to determine if the flavor-template should be applied. |
//    | FlavorParts                    | One or more flavor-part entities that are generated by the template. |
//
//   <b>FlavorParts</b>: The type or classification of the flavor. For more information on flavor parts, see the
//   product guide.
//
//       - PLATFORM
//       - OS
//       - ASSET_TAG
//       - HOST_UNIQUE
//       - SOFTWARE
//
//   Creates a Flavor template and stores it in the database.
//
// x-permissions: flavor-template:create
// security:
//  - bearerAuth: []
// produces:
// - application/json
// consumes:
// - application/json
// parameters:
// - name: request body
//   required: true
//   in: body
//   schema:
//    "$ref": "#/definitions/FlavorTemplate"
// - name: Content-Type
//   required: true
//   in: header
//   type: string
// - name: Accept
//   required: true
//   in: header
//   type: string
// responses:
//   '200':
//     description: Successfully created the flavortemplate.
//     content:
//       application/json
//     schema:
//       $ref: "#/definitions/FlavorTemplate"
//   '400':
//     description: Invalid request body provided
//   '415':
//     description: Invalid Content-Type/Accept Header in Request
//   '500':
//     description: Internal server error
//
// x-sample-call-endpoint: https://hvs.com:8443/hvs/v2/flavortemplate/
// x-sample-call-input: |
//    {
//      "label": "default-pfr",
//      "condition": [
//         "//meta/vendor='Linux'",
//         "//meta/tpm_version/='2.0'"
//       ],
//      "flavor-parts": {
//           "PLATFORM": {
//                "meta": {
//                    "vendor":"Linux",
//                    "tpm_version": "2.0",
//                    "uefi_enabled": true
//                },
//                "pcr_rules": [
//                    {
//                        "pcr": {
//                            "index": 7,
//                            "bank": "SHA256"
//                        },
//                        "eventlog_includes": ["Inte PFR"]
//                    }
//                ]
//            }
//        }
//    }
//
// x-sample-call-output: |
//    {
//        "id": "3f8a57a8-f6d7-49ea-8309-0e00b997fbce",
//        "label": "default-pfr",
//        "condition": [
//            "//meta/vendor='Linux'",
//            "//meta/tpm_version/='2.0'"
//        ],
//        "flavor-parts": {
//            "PLATFORM": {
//                "meta": {
//                    "vendor": "Linux",
//                    "tpm_version": "2.0",
//                    "uefi_enabled": true
//                },
//                "pcr_rules": [
//                    {
//                        "pcr": {
//                            "index": 7,
//                            "bank": "SHA256"
//                        },
//                        "pcr_matches": null,
//                        "eventlog_includes": [
//                            "Inte PFR"
//                        ]
//                    }
//                ]
//            }
//        }
//    }

// ---

// swagger:operation GET /flavor-template/ Flavortemplate Search-FlavorTemplate
// ---
//
// description: |
//   Retrieves all the flavor templates available in the database.
//
// x-permissions: flavor-template:retrieve
// security:
//  - bearerAuth: []
// produces:
// - application/json
// parameters:
// - name: include_deleted
//   description: To include 'lazy-deleted' templates.
//   in: query
//   required: false
//   type: string
//   format: bool
// - name: Accept
//   description: Accept header
//   in: header
//   type: string
//   required: true
//   enum:
//     - application/json
// responses:
//   '200':
//     description: Successfully retrieved the flavortemplate
//     content:
//       application/json
//     schema:
//       $ref: "#/definitions/FlavorTemplate"
//   '400':
//     description: Invalid or Bad request
//   '401':
//     description: Unauthorized request
//   '404':
//     description: Flavortemplate record not found
//   '500':
//     description: Internal server error
//
// x-sample-call-endpoint: https://hvs.com:8443/hvs/v2/flavor-template/
// x-sample-call-output: |
//   [
//     {
//         "id": "d6f81340-b033-4fae-8ccf-795430f486e7",
//         "label": "default_uefi",
//         "condition": [
//             "//meta/vendor='Linux'",
//             "//meta/tpm_version/='2.0'",
//             "//meta/uefi_enabled/='true' or //meta/suefi_enabled/='true'"
//         ],
//         "flavor-parts": {
//             "PLATFORM": {
//                 "meta": {
//                     "vendor": "Linux",
//                     "tpm_version": "2.0",
//                     "uefi_enabled": true
//                 },
//                 "pcr_rules": [
//                     {
//                         "pcr": {
//                             "index": 0,
//                             "bank": "SHA256"
//                         },
//                         "pcr_matches": true
//                     }
//                 ]
//             },
//             "OS": {
//                 "meta": {
//                     "vendor": "Linux",
//                     "tpm_version": "2.0",
//                     "uefi_enabled": true
//                 },
//                 "pcr_rules": [
//                     {
//                         "pcr": {
//                             "index": 7,
//                             "bank": "SHA256"
//                         },
//                         "pcr_matches": null,
//                         "eventlog_includes": [
//                             "shim",
//                             "db",
//                             "kek",
//                             "vmlinuz"
//                         ]
//                     }
//                 ]
//             }
//         }
//     },
//     {
//         "id": "3f8a57a8-f6d7-49ea-8309-0e00b997fbce",
//         "label": "default-pfr",
//         "condition": [
//           "//meta/vendor='Linux'",
//           "//meta/tpm_version/='2.0'"
//         ],
//         "flavor-parts": {
//             "PLATFORM": {
//                 "meta": {
//                     "vendor":"Linux",
//                     "tpm_version": "2.0",
//                     "uefi_enabled": true
//                 },
//                 "pcr_rules": [
//                     {
//                         "pcr": {
//                             "index": 7,
//                             "bank": "SHA256"
//                         },
//                         "eventlog_includes": ["Inte PFR"]
//                     }
//                 ]
//             }
//         }
//     }
//   ]

// ---

// swagger:operation DELETE /flavor-template/{flavortemplate_id} Flavortemplate Delete-FlavorTemplate
// ---
//
// description: |
//   Deletes a flavor template from database.
// x-permissions: flavor-template:delete
// security:
//  - bearerAuth: []
// parameters:
// - name: flavortemplate_id
//   description: Unique ID of the flavortemplate
//   in: path
//   required: true
//   type: string
//   format: uuid
// responses:
//   '204':
//     description: Successfully performed lazy delete on flavor template based on flavortemplate_id
//   '400':
//     description: Invalid or Bad request
//   '401':
//     description: Unauthorized request
//   '404':
//     description: Flavortemplate record not found
//   '500':
//     description: Internal server error
//
// x-sample-call-endpoint: https://hvs.com:8443/hvs/v2/flavor-template/d6f81340-b033-4fae-8ccf-795430f486e7
// x-sample-call-output: |

// ---

// swagger:operation POST /flavor-part/ Flavortemplate Convert-FlavorPart
// ---
// description: |
//   Converts Flavor parts from 3.2 and older versions to latest Flavor part.
//
// x-permissions: flavor-template:create
// security:
//  - bearerAuth: []
// produces:
// - application/json
// consumes:
// - application/json
// parameters:
// - name: request body
//   required: true
//   in: body
//   schema:
//    "$ref": "#/definitions/SignedFlavorCollection"
// - name: Content-Type
//   required: true
//   in: header
//   type: string
// - name: Accept
//   required: true
//   in: header
//   type: string
// responses:
//   '200':
//     description: Successfully created the latest flavorpart from previous flavor part.
//     content:
//       application/json
//     schema:
//       $ref: "#/definitions/FlavorSchema"
//   '400':
//     description: Invalid request body provided
//   '415':
//     description: Invalid Content-Type/Accept Header in Request
//   '500':
//     description: Internal server error
//
// x-sample-call-endpoint: https://hvs.com:8443/hvs/v2/flavor-part/
// x-sample-call-input: |
//  [
//    {
//       "flavor":{
//          "meta":{
//             "id":"4807508d-9d93-4f3b-8da2-0d6dfebb4352",
//             "description":{
//                "flavor_part":"PLATFORM",
//                "source":"localhost.localdomain",
//                "label":"INTEL_IntelCorporation_SE5C620.86B.00.01.0014.070920180847_TPM_TXT_2020-08-21T00:11:46.613123-07:00",
//                "bios_name":"Intel Corporation",
//                "bios_version":"SE5C620.86B.00.01.0014.070920180847",
//                "tpm_version":"2.0",
//                "tboot_installed":"true"
//             },
//             "vendor":"INTEL"
//          },
//          "bios":{
//             "bios_name":"Intel Corporation",
//             "bios_version":"SE5C620.86B.00.01.0014.070920180847"
//          },
//          "hardware":{
//             "processor_info":"54 06 05 00 FF FB EB BF",
//             "processor_flags":"FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE-36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE",
//             "feature":{
//                "TXT":{
//                   "enabled":true
//                },
//                "TPM":{
//                   "enabled":true,
//                   "version":"2.0",
//                   "pcr_banks":[
//                      "SHA1",
//                      "SHA256"
//                   ]
//                }
//             }
//          },
//          "pcrs":{
//             "SHA1":{
//                "pcr_0":{
//                   "value":"3f95ecbb0bb8e66e54d3f9e4dbae8fe57fed96f0"
//                },
//                "pcr_17":{
//                   "value":"efe2d6446e4adf17a32c84e89df1f097997c1ed2",
//                   "event":[
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"19f7c22f6c92d9555d792466b2097443444ebd26",
//                         "label":"HASH_START",
//                         "info":{
//                            "ComponentName":"HASH_START",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"3cf4a5c90911c21f6ea71f4ca84425f8e65a2be7",
//                         "label":"BIOSAC_REG_DATA",
//                         "info":{
//                            "ComponentName":"BIOSAC_REG_DATA",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"3c585604e87f855973731fea83e21fab9392d2fc",
//                         "label":"CPU_SCRTM_STAT",
//                         "info":{
//                            "ComponentName":"CPU_SCRTM_STAT",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"5ba93c9db0cff93f52b521d7420e43f6eda2784f",
//                         "label":"LCP_DETAILS_HASH",
//                         "info":{
//                            "ComponentName":"LCP_DETAILS_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"5ba93c9db0cff93f52b521d7420e43f6eda2784f",
//                         "label":"STM_HASH",
//                         "info":{
//                            "ComponentName":"STM_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"0cf169a95bd32a9a1dc4c3499ade207d30ab8895",
//                         "label":"OSSINITDATA_CAP_HASH",
//                         "info":{
//                            "ComponentName":"OSSINITDATA_CAP_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"55b29518b96e8afa75f32055ed414575f61e50a0",
//                         "label":"MLE_HASH",
//                         "info":{
//                            "ComponentName":"MLE_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"274f929dbab8b98a7031bbcd9ea5613c2a28e5e6",
//                         "label":"NV_INFO_HASH",
//                         "info":{
//                            "ComponentName":"NV_INFO_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"ca96de412b4e8c062e570d3013d2fccb4b20250a",
//                         "label":"tb_policy",
//                         "info":{
//                            "ComponentName":"tb_policy",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      }
//                   ]
//                },
//                "pcr_18":{
//                   "value":"86da61107994a14c0d154fd87ca509f82377aa30",
//                   "event":[
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"a395b723712b3711a89c2bb5295386c0db85fe44",
//                         "label":"SINIT_PUBKEY_HASH",
//                         "info":{
//                            "ComponentName":"SINIT_PUBKEY_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"3c585604e87f855973731fea83e21fab9392d2fc",
//                         "label":"CPU_SCRTM_STAT",
//                         "info":{
//                            "ComponentName":"CPU_SCRTM_STAT",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"0cf169a95bd32a9a1dc4c3499ade207d30ab8895",
//                         "label":"OSSINITDATA_CAP_HASH",
//                         "info":{
//                            "ComponentName":"OSSINITDATA_CAP_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"5ba93c9db0cff93f52b521d7420e43f6eda2784f",
//                         "label":"LCP_AUTHORITIES_HASH",
//                         "info":{
//                            "ComponentName":"LCP_AUTHORITIES_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"274f929dbab8b98a7031bbcd9ea5613c2a28e5e6",
//                         "label":"NV_INFO_HASH",
//                         "info":{
//                            "ComponentName":"NV_INFO_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"ca96de412b4e8c062e570d3013d2fccb4b20250a",
//                         "label":"tb_policy",
//                         "info":{
//                            "ComponentName":"tb_policy",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      }
//                   ]
//                }
//             },
//             "SHA256":{
//                "pcr_0":{
//                   "value":"1009d6bc1d92739e4e8e3c6819364f9149ee652804565b83bf731bdb6352b2a6"
//                },
//                "pcr_17":{
//                   "value":"dbb54f92a3cd889016bf4fe9d08ce450eed6a7e9ab60d7b8f618b44781baf83b",
//                   "event":[
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"14fc51186adf98be977b9e9b65fc9ee26df0599c4f45804fcc45d0bdcf5025db",
//                         "label":"HASH_START",
//                         "info":{
//                            "ComponentName":"HASH_START",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"c61aaa86c13133a0f1e661faf82e74ba199cd79cef652097e638a756bd194428",
//                         "label":"BIOSAC_REG_DATA",
//                         "info":{
//                            "ComponentName":"BIOSAC_REG_DATA",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"67abdd721024f0ff4e0b3f4c2fc13bc5bad42d0b7851d456d88d203d15aaa450",
//                         "label":"CPU_SCRTM_STAT",
//                         "info":{
//                            "ComponentName":"CPU_SCRTM_STAT",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d",
//                         "label":"LCP_DETAILS_HASH",
//                         "info":{
//                            "ComponentName":"LCP_DETAILS_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d",
//                         "label":"STM_HASH",
//                         "info":{
//                            "ComponentName":"STM_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"d81fe96dc500bc43e1cd5800bef9d72b3d030bdb7e860e10c522e4246b30bd93",
//                         "label":"OSSINITDATA_CAP_HASH",
//                         "info":{
//                            "ComponentName":"OSSINITDATA_CAP_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"89b2829048f5ee138a25e528cbd1da64f32fa1b484a369581288868ee2e7a549",
//                         "label":"MLE_HASH",
//                         "info":{
//                            "ComponentName":"MLE_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"0f6e0c7a5944963d7081ea494ddff1e9afa689e148e39f684db06578869ea38b",
//                         "label":"NV_INFO_HASH",
//                         "info":{
//                            "ComponentName":"NV_INFO_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"27808f64e6383982cd3bcc10cfcb3457c0b65f465f779d89b668839eaf263a67",
//                         "label":"tb_policy",
//                         "info":{
//                            "ComponentName":"tb_policy",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      }
//                   ]
//                },
//                "pcr_18":{
//                   "value":"d9e55bd1c570a6408fb1368f3663ae92747241fc4d2a3622cef0efadae284d75",
//                   "event":[
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"da256395df4046319ef0af857d377a729e5bc0693429ac827002ffafe485b2e7",
//                         "label":"SINIT_PUBKEY_HASH",
//                         "info":{
//                            "ComponentName":"SINIT_PUBKEY_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"67abdd721024f0ff4e0b3f4c2fc13bc5bad42d0b7851d456d88d203d15aaa450",
//                         "label":"CPU_SCRTM_STAT",
//                         "info":{
//                            "ComponentName":"CPU_SCRTM_STAT",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"d81fe96dc500bc43e1cd5800bef9d72b3d030bdb7e860e10c522e4246b30bd93",
//                         "label":"OSSINITDATA_CAP_HASH",
//                         "info":{
//                            "ComponentName":"OSSINITDATA_CAP_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d",
//                         "label":"LCP_AUTHORITIES_HASH",
//                         "info":{
//                            "ComponentName":"LCP_AUTHORITIES_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"0f6e0c7a5944963d7081ea494ddff1e9afa689e148e39f684db06578869ea38b",
//                         "label":"NV_INFO_HASH",
//                         "info":{
//                            "ComponentName":"NV_INFO_HASH",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      },
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"27808f64e6383982cd3bcc10cfcb3457c0b65f465f779d89b668839eaf263a67",
//                         "label":"tb_policy",
//                         "info":{
//                            "ComponentName":"tb_policy",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      }
//                   ]
//                }
//             }
//          }
//       },
//       "signature":"QTpd7Hupxu196puAAQ953TgWQpWDW3IT40abiCfHN4CpV53Ke9tYfrzRzpX3vCsWBfmkd3AdVRlhUDlH02tOxOTUiAJN35abYe/PHM1rQG3j7uuK9IH65VE3rCFUxXwnfclwNH1+5sxmMcvKZVYvZQTHJdzr9M1Efo0RXioK+GoUJZzN956QSc22Z97Na5aVD5pPO7A5gCYj1BNkQS2sRmiVKdPOfcsYFUHwD5G4+CIjwzZqH1etAeYFNsW8tKnJKa3CWQ17NpgmFy0INClG3Tyubt7PpdZyGsu0anAUfH4x9h2pDlpm37cs4WNKJmgshsaA/RujxY6Kc4+YGdEEAN9l5RSnnfNSdgDKmrwkL2jNnxPky+PpSXNLr5927NlSXRJ1iJU/9mx6cG6ssZXVItGsEHbWj/uCn8xJ9Pls4Zm3C/UGUk6QmYNl8R3GultS4qaLs2eYHeU9xPIhuSXXAHlzZEsKSY/z94jWyDpkHk8hq3ODSlN3EW5NZqt9zWNP"
//    },
//    {
//       "flavor":{
//          "meta":{
//             "id":"98c911c5-72a2-42a8-84b4-eb45bc422d4f",
//             "description":{
//                "flavor_part":"OS",
//                "source":"localhost.localdomain",
//                "label":"INTEL_RedHatEnterprise_8.2_Docker_19.03.12_2020-08-21T00:11:46.631501-07:00",
//                "os_name":"RedHatEnterprise",
//                "os_version":"8.2",
//                "vmm_name":"Docker",
//                "vmm_version":"19.03.12",
//                "tpm_version":"2.0",
//                "tboot_installed":"true"
//             },
//             "vendor":"INTEL"
//          },
//          "bios":{
//             "bios_name":"Intel Corporation",
//             "bios_version":"SE5C620.86B.00.01.0014.070920180847"
//          },
//          "pcrs":{
//             "SHA1":{
//                "pcr_17":{
//                   "value":"efe2d6446e4adf17a32c84e89df1f097997c1ed2",
//                   "event":[
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha1",
//                         "value":"fbe8c6890de8cce6422637beac0a28b32f6939b1",
//                         "label":"vmlinuz",
//                         "info":{
//                            "ComponentName":"vmlinuz",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      }
//                   ]
//                }
//             },
//             "SHA256":{
//                "pcr_17":{
//                   "value":"dbb54f92a3cd889016bf4fe9d08ce450eed6a7e9ab60d7b8f618b44781baf83b",
//                   "event":[
//                      {
//                         "digest_type":"com.intel.mtwilson.core.common.model.MeasurementSha256",
//                         "value":"d4b319df2b01841ab98398dca33d8fcefcada45c40456711fa9b8551cf832649",
//                         "label":"vmlinuz",
//                         "info":{
//                            "ComponentName":"vmlinuz",
//                            "EventName":"OpenSource.EventName"
//                         }
//                      }
//                   ]
//                }
//             }
//          }
//       },
//       "signature":"RrO9buU5JTe78dZqE4LKowYWRg7lSL8Gzx9RwqSbhfL/e5qvKSsr669kz8aRMLZbxTJDmHlJedmASuejhxpCZEd2cSt1/z8rL8axuqLlhexv5tZ5JI4pO/lXxV3K5uWGi9x7kRLvGGw3RME53eJZsFiZWOGIxGfKTPcYsoR2+3ReMeoJkhdtjnvkdLSQM/o61pPDb+jW/JZiI2WuB383b1L+hC+I20t1NNt2Vs6092h8Qzfpsj/BD6AG3FE75SwjfQVMZKB6zbWb1OQpIDBT7niHHyDhvGv44MZ6f81bbwlHcGO1SwzKVJuiOq24oI5cXj+S2xJ5Mu2Kuhx1gXKUVX84qk0DWbYPY0mMra7ECLU/06HrA8hYubcvFN2CG4TCltliSgFoBL1OLsosc25Y3thNQgZCVPQavLxfy+E82zjpb79wU8HY7MrJ61YvbIh+g3rfdL+a4o713XkZJ+lBRuO2ETxqry1pohJV4fAPwTcdTZ8/hucrVwoySDZG1iWT"
//    }
//  ]
// x-sample-call-output: |
//   [
//     {
//         "id": "890bc756-40da-4bde-a707-3b27b23e0149",
//         "flavor_part": "PLATFORM",
//         "meta": {
//             "template_id": "3392f153-705b-47b2-aa81-d699c57d9568",
//             "template_label": "linux-tpm2-tboot",
//             "source": "computer1.intel.com",
//             "bios_name": "Intel Corporation",
//             "bios_version": "SE5C620.86B.0X.01.0155.073020181001",
//             "tboot_installed": "true"
//         },
//         "pcrs": [
//             {
//                 "pcr": {
//                     "index": 0,
//                     "bank": "SHA256"
//                 },
//                 "measurement": "987c560472a458a563a21e33b2e927383c7d379340d5a98c8529ab82ecda79f9",
//                 "pcr_matches": true
//             },
//             {
//                 "pcr": {
//                     "index": 17,
//                     "bank": "SHA256"
//                 },
//                 "measurement": "9b34aeaec0aa4073c63c37d607e4d039203444318adf204b9ecbf1e6a853467d",
//                 "eventlog_equals": {
//                     "tpm_events": [
//                         {
//                             "type_id": 900,
//                             "measurement": "940a487b3a2b3a82858b18c20f55ad9c73522f43aab071f62350093bd7c2d6ba",
//                             "tags": ["HASH_START"]
//                         },
//                         {
//                             "type_id": 901,
//                             "measurement": "7980d1a2034e18a33da6fde28ddd8a296c7147a3e4cea6dc32997f4fc40a97a5",
//                             "tags": ["BIOSAC_REG_DATA"]
//                         }
//                     ],
//                     "exclude_tags": ["commandLine."]
//                 }
//             }
//         ]
//     },
//     {
//         "id": "61a8c756-40da-4bde-a707-3b27b23e0149",
//         "flavor_part": "OS",
//         "meta": {
//             "template_id": "3392f153-705b-47b2-aa81-d699c57d9568",
//             "template_label": "linux-tpm2-tboot",
//             "source": "computer1.intel.com",
//             "os_name": "RedHatEnterprise",
//             "os_version": "8.1",
//             "vmm_name": "Docker",
//             "vmm_version": "19.03.5",
//             "tpm_version": "2.0",
//             "tboot_installed": "true"
//         },
//         "pcrs": [
//             {
//                 "pcr": {
//                     "index": 17,
//                     "bank": "SHA256"
//                 },
//                 "measurement": "9b34aeaec0aa4073c63c37d607e4d039203444318adf204b9ecbf1e6a853467d",
//                 "eventlog_includes": [
//                     {
//                         "type_id": 409,
//                         "measurement": "eaa699b0d1f10fd7eccdcab9813b174f68b4327b022bf05e93a38b17c1c8e8dc",
//                         "tags": ["vmlinuz"]
//                     }
//                 ]
//             }
//         ]
//     }
//    ]

// ---
